version: '3.7'

services:
  crud:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:80
    volumes:
      - "./:/var/www/html"
      - "./bin/000-default.conf:/etc/apache2/sites-available/000-default.conf"

  mariadb:
    image: mariadb:10.5.2
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "Asia/Tashkent"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testpassword'
      MYSQL_DATABASE: 'testdb'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'mariadb:db'
    ports:
      - 8081:80

volumes:
  mariadb-volume:
