<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\Apple::class => App\Handler\AppleFactory::class,
            App\Handler\AppleHandler::class => App\Handler\AppleHandlerFactory::class,
            App\Handler\CreateHandler::class => App\Handler\CreateHandlerFactory::class,
            App\Handler\DeleteUserHandler::class => App\Handler\DeleteUserHandlerFactory::class,
            App\Handler\EditUserInfoHandler::class => App\Handler\EditUserInfoHandlerFactory::class,
            App\Handler\HelloHandler::class => App\Handler\HelloHandlerFactory::class,
            App\Handler\HomePageHandler::class => App\Handler\HomePageHandlerFactory::class,
        ],
    ],
];
